"""empty message
drop the unique=>didnt know how to solve it from app.py, not good way but figure it out later
Revision ID: 534d75d9331a
Revises: bb828c6ec63e
Create Date: 2022-04-08 18:00:11.913516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534d75d9331a'
down_revision = 'bb828c6ec63e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_name_key', 'artist', type_='unique')
    op.drop_constraint('venue_name_key', 'venue', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('venue_name_key', 'venue', ['name'])
    op.create_unique_constraint('artist_name_key', 'artist', ['name'])
    # ### end Alembic commands ###
